IF OBJECT_ID('tempdb..#StageData') IS NOT NULL DROP TABLE #StageData
CREATE TABLE #StageData (
  LeaveAccrualChangeDate DATE
 ,EmployeeId INT
 ,Employee_Number VARCHAR(7)
 ,LAC_LVE_TYPE VARCHAR(4) NULL
 ,LAC_AS_AT_DT DATE NULL
 ,LAC_SRV_STRT DATE NULL
 ,LAC_ENT_DATE DATE NULL
 ,LAC_ACC_DAYS FLOAT NULL
 ,LAC_ACC_HRS FLOAT NULL
 ,LAC_ENT_DAYS FLOAT NULL
 ,LAC_ENT_HRS FLOAT NULL
 ,LAC_CALC_RUN DATE NULL
 ,LAC_CUR_AC_D FLOAT NULL
 ,LAC_CUR_AC_H FLOAT NULL
 ,LAC_TOT_DAYS FLOAT NULL
 ,LAC_TOT_HRS FLOAT NULL
 ,LAC_LVE_DAYS FLOAT NULL
 ,LAC_LVE_HRS FLOAT NULL
 ,LAC_PAST_DAY FLOAT NULL
 ,LAC_PAST_HRS FLOAT NULL
 ,LAC_SRV_YRS INT NULL
 ,LAC_SRV_DAYS INT NULL
 ,LAC_CUR_EN_D FLOAT NULL
 ,LAC_CUR_EN_H FLOAT NULL
 ,LAC_LAST_ENT NVARCHAR(10) NULL
 ,LAC_ADJ_DAYS FLOAT NULL
 ,LAC_ADJ_HRS FLOAT NULL
 ,LAC_NEXT_ENT NVARCHAR(10) NULL
)

INSERT INTO #StageData (EmployeeId
, Employee_Number
, LAC_LVE_TYPE
, LAC_AS_AT_DT
, LAC_SRV_STRT
, LAC_ENT_DATE
, LAC_ACC_DAYS
, LAC_ACC_HRS
, LAC_ENT_DAYS
, LAC_ENT_HRS
, LAC_CALC_RUN
, LAC_CUR_AC_D
, LAC_CUR_AC_H
, LAC_TOT_DAYS
, LAC_TOT_HRS
, LAC_LVE_DAYS
, LAC_LVE_HRS
, LAC_PAST_DAY
, LAC_PAST_HRS
, LAC_SRV_YRS
, LAC_SRV_DAYS
, LAC_CUR_EN_D
, LAC_CUR_EN_H
, LAC_LAST_ENT
, LAC_ADJ_DAYS
, LAC_ADJ_HRS
, LAC_NEXT_ENT)

  SELECT
   DimEmployee.Id 
   ,Staging_EMLAC.DET_NUMBER
   ,Staging_EMLAC.LAC_LVE_TYPE
   ,CAST(Staging_EMLAC.LAC_AS_AT_DT AS DATE) LAC_AS_AT_DT
   ,CAST(Staging_EMLAC.LAC_SRV_STRT AS DATE) LAC_SRV_STRT
   ,CAST(Staging_EMLAC.LAC_ENT_DATE AS DATE) LAC_ENT_DATE
   ,Staging_EMLAC.LAC_ACC_DAYS
   ,Staging_EMLAC.LAC_ACC_HRS
   ,Staging_EMLAC.LAC_ENT_DAYS
   ,Staging_EMLAC.LAC_ENT_HRS
   ,CAST(Staging_EMLAC.LAC_CALC_RUN AS DATE) LAC_CALC_RUN
   ,Staging_EMLAC.LAC_CUR_AC_D
   ,Staging_EMLAC.LAC_CUR_AC_H
   ,Staging_EMLAC.LAC_TOT_DAYS
   ,Staging_EMLAC.LAC_TOT_HRS
   ,Staging_EMLAC.LAC_LVE_DAYS
   ,Staging_EMLAC.LAC_LVE_HRS
   ,Staging_EMLAC.LAC_PAST_DAY
   ,Staging_EMLAC.LAC_PAST_HRS
   ,Staging_EMLAC.LAC_SRV_YRS
   ,Staging_EMLAC.LAC_SRV_DAYS
   ,Staging_EMLAC.LAC_CUR_EN_D
   ,Staging_EMLAC.LAC_CUR_EN_H
   ,Staging_EMLAC.LAC_LAST_ENT
   ,Staging_EMLAC.LAC_ADJ_DAYS
   ,Staging_EMLAC.LAC_ADJ_HRS
   ,Staging_EMLAC.LAC_NEXT_ENT
  FROM DataWarehouseChris21RawData.dbo.Staging_EMLAC
  INNER JOIN DataWarehouseChris21.dbo.DimEmployee
  ON DimEmployee.DET_NUMBER = Staging_EMLAC.DET_NUMBER

INSERT INTO dbo.FactLeaveAccrual (LeaveAccrualChangeDate
, EmployeeId
, Employee_Number
, LAC_LVE_TYPE
, LAC_AS_AT_DT
, LAC_SRV_STRT
, LAC_ENT_DATE
, LAC_ACC_DAYS
, LAC_ACC_HRS
, LAC_ENT_DAYS
, LAC_ENT_HRS
, LAC_CALC_RUN
, LAC_CUR_AC_D
, LAC_CUR_AC_H
, LAC_TOT_DAYS
, LAC_TOT_HRS
, LAC_LVE_DAYS
, LAC_LVE_HRS
, LAC_PAST_DAY
, LAC_PAST_HRS
, LAC_SRV_YRS
, LAC_SRV_DAYS
, LAC_CUR_EN_D
, LAC_CUR_EN_H
, LAC_LAST_ENT
, LAC_ADJ_DAYS
, LAC_ADJ_HRS
, LAC_NEXT_ENT)

  SELECT
    CAST(GETDATE() AS DATE) AS LeaveAccrualChangeDate
   ,EmployeeId
   ,Employee_Number
   ,LAC_LVE_TYPE
   ,LAC_AS_AT_DT
   ,LAC_SRV_STRT
   ,LAC_ENT_DATE
   ,LAC_ACC_DAYS
   ,LAC_ACC_HRS
   ,LAC_ENT_DAYS
   ,LAC_ENT_HRS
   ,LAC_CALC_RUN
   ,LAC_CUR_AC_D
   ,LAC_CUR_AC_H
   ,LAC_TOT_DAYS
   ,LAC_TOT_HRS
   ,LAC_LVE_DAYS
   ,LAC_LVE_HRS
   ,LAC_PAST_DAY
   ,LAC_PAST_HRS
   ,LAC_SRV_YRS
   ,LAC_SRV_DAYS
   ,LAC_CUR_EN_D
   ,LAC_CUR_EN_H
   ,LAC_LAST_ENT
   ,LAC_ADJ_DAYS
   ,LAC_ADJ_HRS
   ,LAC_NEXT_ENT
  FROM #StageData StageData
  WHERE NOT EXISTS (SELECT *
    FROM FactLeaveAccrual
    WHERE FactLeaveAccrual.LAC_CALC_RUN = StageData.LAC_CALC_RUN)
DROP TABLE #StageData

